api_platform:
    title: Pizzaman API Platform
    version: 0.0.1
    mapping:
        paths:
            - '%kernel.project_dir%/config/api'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
